// ============================================================
// events.js — 奥克兰文化贴纸地图 · 活动数据（唯一需要每周更新的文件）
// generated：数据更新日期，页面顶部会显示"数据更新于 X"——每次改动必须更新！
// 示例条目：title 以 "Sample:" 开头（页面自动挂"示例数据"徽章）；真实数据勿用此前缀。
// item 字段: venue 场馆id | title/zh 标题 | date "YYYY-MM-DD" | kind | url
//   可选: end 撤展日(仅 exhibition) | time "7pm" | price "free"|"paid"|"koha"
//        | desc/descZh 一句话双语简介
// kind: exhibition 长期展(卡片显示"正在展出") | opening 开幕 | reading 文学
//       | gig 演出 | workshop 工作坊 | market 集市 | talk 讲座 | film 放映
// ============================================================
window.EVENTS = {
  generated: "2026-07-07",
  sample: true,
  items: [
    /* ---- 奥克兰美术馆：真实展讯（2026-07-07 检索；展期以官网为准） ---- */
    { venue: "aag", title: "Forever Tomorrow: Chinese Art Now", zh: "《永远的明天：中国当代艺术》", kind: "exhibition", date: "2026-06-01", end: "2026-09-30", price: "paid",
      desc: "Major ticketed survey of Chinese contemporary art — sculpture, photography, digital works. Adults $22. End date TBC, see gallery site.",
      descZh: "中国当代艺术大展：雕塑、摄影、数字作品。成人 $22。展期以官网为准。",
      url: "https://www.aucklandartgallery.com/" },
    { venue: "aag", title: "In Trust for Tomorrow: The Greg J Moyle Foundation Bequest", zh: "《为明天而藏》：Moyle 基金会捐赠展", kind: "exhibition", date: "2026-05-23", end: "2026-09-30", price: "free",
      desc: "20 major New Zealand works promised to the Gallery by collector Greg Moyle. Free entry. End date TBC.",
      descZh: "收藏家 Greg Moyle 允诺捐赠的 20 件新西兰重要作品。免费。展期以官网为准。",
      url: "https://www.aucklandartgallery.com/" },
    { venue: "aag", title: "Taimoana | Coastlines: Art in Aotearoa (collection)", zh: "馆藏陈列《Taimoana | 海岸线》", kind: "exhibition", date: "2026-02-01", end: "2026-12-31", price: "free",
      desc: "Collection exhibition programmed through 2026, with regular changeouts. Also on: Giacometti Without End; Ngā Taonga Tūturu; Threads of Time.",
      descZh: "贯穿 2026 年的馆藏陈列，定期换展。同期还有《贾科梅蒂》《玛欧里肖像珍藏》《时间之线》。",
      url: "https://www.aucklandartgallery.com/visit/exhibitions" },
    { venue: "poetrylive", title: "Poetry Live — open mic (every Tuesday)",  zh: "Poetry Live 开放麦（每周二）", date: "2026-07-14", kind: "reading", price: "koha",
      desc: "Aotearoa's longest-running live poetry night, Tuesdays at the Thirsty Dog. Check their socials to confirm.",
      descZh: "新西兰持续最久的现场诗歌之夜，每周二在 Thirsty Dog。出发前查其社媒确认。",
      url: "https://www.facebook.com/poetrylive/" },
    { venue: "poetrylive", title: "Poetry Live — open mic (every Tuesday)",  zh: "Poetry Live 开放麦（每周二）", date: "2026-07-21", kind: "reading", price: "koha",
      desc: "Weekly open mic — guest poet + live music. Check socials to confirm.",
      descZh: "每周开放麦：特邀诗人+现场音乐。出发前查其社媒确认。",
      url: "https://www.facebook.com/poetrylive/" },
    { venue: "poetrylive", title: "Poetry Live — open mic (every Tuesday)",  zh: "Poetry Live 开放麦（每周二）", date: "2026-07-28", kind: "reading", price: "koha",
      desc: "Weekly open mic — guest poet + live music. Check socials to confirm.",
      descZh: "每周开放麦：特邀诗人+现场音乐。出发前查其社媒确认。",
      url: "https://www.facebook.com/poetrylive/" },
    { venue: "poetrylive", title: "Poetry Live — open mic (every Tuesday)",  zh: "Poetry Live 开放麦（每周二）", date: "2026-08-04", kind: "reading", price: "koha",
      desc: "Weekly open mic — guest poet + live music. Check socials to confirm.",
      descZh: "每周开放麦：特邀诗人+现场音乐。出发前查其社媒确认。",
      url: "https://www.facebook.com/poetrylive/" },
    /* ---- 固定周期集市：真实的每周集市（脚本上线后自动续期） ---- */
    { venue: "britomart",  title: "Britomart Saturday Markets",  zh: "Britomart 周六集市",  date: "2026-07-11", kind: "market", price: "free", time: "8am–2pm",
      desc: "Weekly artisan and produce market at Te Komititanga square.", descZh: "Te Komititanga 广场的每周手作与农产集市。", url: "https://britomart.org/" },
    { venue: "britomart",  title: "Britomart Saturday Markets",  zh: "Britomart 周六集市",  date: "2026-07-18", kind: "market", price: "free", time: "8am–2pm",
      desc: "Weekly artisan and produce market at Te Komititanga square.", descZh: "Te Komititanga 广场的每周手作与农产集市。", url: "https://britomart.org/" },
    { venue: "lacigale",   title: "La Cigale French Market",     zh: "La Cigale 法式集市",  date: "2026-07-11", kind: "market", price: "free", time: "Sat 8am–1.30pm",
      desc: "Parnell's long-running French market — produce, pastries, brocante.", descZh: "Parnell 老牌法式集市：农产、法点、旧货。", url: "https://lacigale.co.nz/" },
    { venue: "lacigale",   title: "La Cigale French Market",     zh: "La Cigale 法式集市",  date: "2026-07-12", kind: "market", price: "free", time: "Sun 9am–1.30pm",
      desc: "Sunday edition of the French market.", descZh: "法式集市周日场。", url: "https://lacigale.co.nz/" },
    { venue: "avondale",   title: "Avondale Sunday Markets",     zh: "Avondale 周日集市",   date: "2026-07-12", kind: "market", price: "free", time: "6am–12pm",
      desc: "Auckland's biggest multicultural market at the racecourse.", descZh: "赛马场上的全奥克兰最大多元文化集市。", url: "https://avondalesundaymarkets.co.nz/" },
    { venue: "avondale",   title: "Avondale Sunday Markets",     zh: "Avondale 周日集市",   date: "2026-07-19", kind: "market", price: "free", time: "6am–12pm",
      desc: "Auckland's biggest multicultural market at the racecourse.", descZh: "赛马场上的全奥克兰最大多元文化集市。", url: "https://avondalesundaymarkets.co.nz/" },
    { venue: "tetuhi",     title: "Six winter exhibitions — final weeks", zh: "六个冬季展览（最后两周）", kind: "exhibition", date: "2026-05-24", end: "2026-07-19", price: "free",
      desc: "Allan McDonald, Bahar Noorizadeh, Brendan Kitto, Ilish Thomas, Pao Houa Her & Sonic Hapori — photography, film, sound, installation. All close 19 Jul.",
      descZh: "六展同期：摄影、影像、声音与装置（McDonald、Noorizadeh、Kitto、Thomas、Pao Houa Her、Sonic Hapori），7月19日同日闭幕。",
      url: "https://tetuhi.art/current-exhibitions/" },
    { venue: "otaramarket", title: "Ōtara Flea Market",           zh: "Ōtara 周六集市",      date: "2026-07-11", kind: "market", price: "free", time: "6am–12pm",
      desc: "South Auckland's iconic Saturday market — Pasifika food, crafts, produce.", descZh: "南奥克兰标志性周六集市：太平洋美食、手作与农产。", url: "https://www.otarafleamarket.co.nz/" },
    { venue: "otaramarket", title: "Ōtara Flea Market",           zh: "Ōtara 周六集市",      date: "2026-07-18", kind: "market", price: "free", time: "6am–12pm",
      desc: "South Auckland's iconic Saturday market.", descZh: "南奥克兰标志性周六集市。", url: "https://www.otarafleamarket.co.nz/" },
    { venue: "ostend",     title: "Ostend Market (Waiheke)",      zh: "Ostend 集市（激流岛）", date: "2026-07-11", kind: "market", price: "free", time: "Sat 8am–1pm",
      desc: "Waiheke's Saturday community market at Ostend Hall.", descZh: "激流岛 Ostend 会堂的周六社区集市。", url: "https://www.waihekemarket.co.nz/" },
    { venue: "ostend",     title: "Ostend Market (Waiheke)",      zh: "Ostend 集市（激流岛）", date: "2026-07-18", kind: "market", price: "free", time: "Sat 8am–1pm",
      desc: "Waiheke's Saturday community market at Ostend Hall.", descZh: "激流岛 Ostend 会堂的周六社区集市。", url: "https://www.waihekemarket.co.nz/" },
    /* ---- 以下为 2026-07-07 校准时抓到的真实数据 ----
       可选字段：time 时间, price "free"|"paid"|"koha"(缺省=费用见链接),
       desc/descZh 一句话简介 */
    { venue: "northart",   title: "Arrested Practice + SELECT — three shows open", zh: "Arrested Practice 等三展同日开幕", date: "2026-07-18", kind: "opening", price: "free",
      desc: "Ten artists revisit 'unfinished' works (Karl Amundsen, Ross Ritchie, Allie Eagle & more), alongside SELECT by Dornwell Studios painters. Gallery entry free, daily 10am–4pm.",
      descZh: "十位艺术家重访“未完成”之作（Karl Amundsen、Ross Ritchie、Allie Eagle 等），同场还有 Dornwell 工作室画家群展 SELECT。免费入场，每日 10am–4pm。",
      url: "https://www.northart.co.nz/" },
    { venue: "northart",   title: "Drisana Tonga: Heliaki | In Between Worlds — opens", zh: "Drisana Tonga《Heliaki》开幕", date: "2026-07-18", kind: "opening", price: "free",
      desc: "Paintings tracing how one culture and way of thinking transitions into another — heliaki: to say one thing and mean another.",
      descZh: "以笔触表达文化之间的相互流转——heliaki 意为“言此而意彼”。",
      url: "https://www.northart.co.nz/" },
    { venue: "northart",   title: "Meet the Artists (Arrested Practice)",    zh: "艺术家见面会（Arrested Practice）", date: "2026-07-31", kind: "talk", time: "2pm", price: "free",
      desc: "Meet the ten artists behind Arrested Practice at Northart, Norman King Square, Northcote.",
      descZh: "与 Arrested Practice 的十位参展艺术家见面。地点：Northcote Norman King 广场 Northart。",
      url: "https://www.northart.co.nz/" },
    { venue: "gowlangsford", title: "Michael Hight: The Seasons — opens (City space)", zh: "Michael Hight《The Seasons》开幕（City 空间）", date: "2026-07-08", kind: "opening", price: "free",
      desc: "New landscapes traversing Aotearoa's shifting seasons, from summer in the Maniototo to spring in the Waitaki Valley. 8 Jul – 8 Aug.",
      descZh: "新风景系列：从 Maniototo 的盛夏到 Waitaki 河谷的初春。展期 7月8日–8月8日。",
      url: "https://gowlangsfordgallery.co.nz/exhibitions/529-the-seasons-michael-hight/" },
    { venue: "gowlangsford", title: "John Pule: the first incision I saw I dreamed no more — opens (Onehunga)", zh: "John Pule 新展开幕（Onehunga 旗舰空间）", date: "2026-08-01", kind: "opening", price: "free",
      desc: "Recent paintings and works on paper shaped by memory, spirituality and lived experience in Niue. 1 Aug – 5 Sep.",
      descZh: "以纽埃的记忆、灵性与生活经验为底色的近作绘画与纸上作品。展期 8月1日–9月5日。",
      url: "https://gowlangsfordgallery.co.nz/exhibitions/526-the-first-incision-i-saw-i-dreamed-no-john-pule/" },
    { venue: "teuru",      title: "Film Screening: From the Breach",         zh: "放映：From the Breach",   date: "2026-07-18", kind: "film", time: "7pm",
      desc: "Evening film screening at Te Uru, 420 Titirangi Rd. See event page for tickets.",
      descZh: "Te Uru 晚间放映，地址 420 Titirangi Rd。票务详见活动页。",
      url: "https://teuru.org.nz/products/film-screening-from-the-breach-1" },
    { venue: "teuru",      title: "Herehere: a Panel Discussion",            zh: "Herehere 座谈会",         date: "2026-07-25", kind: "talk", time: "11am", price: "free",
      desc: "Panel discussion accompanying Herehere — Tāmaki Makaurau as a meeting place (Sione Faletau, Kauri Hawkins, Raymond Sagapolutele).",
      descZh: "配合展览 Herehere 的座谈：奥克兰作为“百人之恋”的相遇之地。",
      url: "https://teuru.org.nz/products/herehere-a-panel-discussion" },
    { venue: "teuru",      title: "Talk & Draw — Gold Card Holders",         zh: "Talk & Draw（长者场）",   date: "2026-07-30", kind: "workshop", time: "10–11.30am", price: "free",
      desc: "Morning gallery talk and drawing session for Gold Card holders.",
      descZh: "面向 Gold Card 长者的上午导览+写生活动。",
      url: "https://teuru.org.nz/products/talk-draw-gold-card-holders" },
    { venue: "teuru",      title: "Nikau Hindin: Manu Aute Workshop",        zh: "Nikau Hindin 玛欧里风筝工作坊", date: "2026-08-01", kind: "workshop", time: "10am", price: "paid",
      desc: "Māori kite-making workshop with artist Nikau Hindin (COSMOLOGIES). Bookings via event page.",
      descZh: "跟随艺术家 Nikau Hindin（COSMOLOGIES 参展人）学做玛欧里传统风筝，需在活动页报名。",
      url: "https://teuru.org.nz/products/nikau-hindin-manu-aute-workshop" },

    /* ---- 正在展出（kind:"exhibition"，date=开展 end=撤展）· 2026-07-07 真实数据 ---- */
    { venue: "gusfisher", title: "Studies for a Keepsake: Claude Cahun and Marcel Moore", zh: "《留念习作》：Claude Cahun 与 Marcel Moore", kind: "exhibition", date: "2026-05-29", end: "2026-08-22", price: "free",
      desc: "Photographs by the French surrealist duo, courtesy of Jersey Heritage Collections. Tue–Fri 10–5, Sat 10–4, free.",
      descZh: "法国超现实主义双人组合的摄影，展品来自泽西岛遗产收藏。免费。",
      url: "https://gusfishergallery.auckland.ac.nz/exhibitions/" },
    { venue: "gusfisher", title: "The Changing Room: Lucy Meyle — Phone Tree", zh: "The Changing Room：Lucy Meyle《Phone Tree》", kind: "exhibition", date: "2026-05-29", end: "2026-08-22", price: "free",
      desc: "New commission by Lucy Meyle (Aotearoa) in the Changing Room space.",
      descZh: "Lucy Meyle 在 Changing Room 空间的新委托创作。",
      url: "https://gusfishergallery.auckland.ac.nz/the-changing-room-lucy-meyle/" },
    { venue: "artspace", title: "CRIT: Art learning since 1987 — opens 18 Jul", zh: "《CRIT：1987 年以来的艺术教育》开幕", kind: "opening", date: "2026-07-18", price: "free",
      desc: "Group show on art education since 1987 — Fiona Connor, Lana Lopesi, Samoa House Library & more. Part of 2026 theme 'which history?'. 18 Jul – 26 Sep.",
      descZh: "关于艺术教育的群展（Fiona Connor、Lana Lopesi、Samoa House Library 等），年度命题“哪一种历史？”第三部。展期 7月18日–9月26日。",
      url: "https://artspace-aotearoa.nz/exhibitions/crit-art-learning-since-1987" },
    { venue: "objectspace", title: "He maramara tupu aranga: Carin Wilson and 50 years of Aotearoa design", zh: "Carin Wilson 与新西兰设计 50 年", kind: "exhibition", date: "2026-06-27", end: "2026-08-30", price: "free",
      desc: "Survey of master carver-designer Carin Wilson (Ngāti Awa) and five decades of Aotearoa design.",
      descZh: "雕刻家/设计师 Carin Wilson（Ngāti Awa）与新西兰设计五十年回顾。",
      url: "https://www.objectspace.org.nz/exhibitions/he-maramara-tupu-aranga-carin-wilson-and/" },
    { venue: "objectspace", title: "walking sticks & canes", zh: "《手杖》", kind: "exhibition", date: "2026-06-27", end: "2026-08-30", price: "free",
      desc: "Exhibition on the craft and design of walking sticks and canes.",
      descZh: "关于手杖工艺与设计的展览。",
      url: "https://www.objectspace.org.nz/exhibitions/walking-sticks-canes/" },
    { venue: "objectspace", title: "Espejo Humeante — final weeks", zh: "《Espejo Humeante》（即将闭幕）", kind: "exhibition", date: "2026-06-27", end: "2026-07-19", price: "free",
      desc: "Closes 19 July.",
      descZh: "7月19日闭幕。",
      url: "https://www.objectspace.org.nz/exhibitions/espejo-humeante/" },
    { venue: "whammy", title: "Oscar Dowling — album release show", zh: "Oscar Dowling 专辑发布演出", date: "2026-07-10", kind: "gig", time: "8pm", price: "paid",
      desc: "At Whammy Bar, St Kevins Arcade. Tickets via UTR.",
      descZh: "Whammy Bar（St Kevins Arcade）。UTR 购票。",
      url: "https://www.undertheradar.co.nz/venue/316/Whammy-Bar.utr" },
    { venue: "whammy", title: "Vampire Disko: goth, wave, cult hits", zh: "Vampire Disko 哥特/新浪潮之夜", date: "2026-07-17", kind: "gig", time: "9pm", price: "paid",
      desc: "Goth, wave and cult hits — vampire attire encouraged.",
      descZh: "哥特、新浪潮与邪典金曲，欢迎吸血鬼装扮。",
      url: "https://www.undertheradar.co.nz/venue/316/Whammy-Bar.utr" },
    { venue: "whammy", title: "King Parrot — Auckland", zh: "King Parrot 奥克兰场", date: "2026-07-18", kind: "gig", time: "8pm", price: "paid",
      desc: "Australian extreme metal at Whammy Bar.",
      descZh: "澳洲极端金属乐队 Whammy 现场。",
      url: "https://www.undertheradar.co.nz/venue/316/Whammy-Bar.utr" },
    { venue: "michaellett", title: "Peter Stichbury: Grand Guignol", zh: "Peter Stichbury《Grand Guignol》", kind: "exhibition", date: "2026-06-11", end: "2026-07-11", price: "free",
      desc: "Current show at Lett Thomas, 312 Karangahape Rd. Wed–Fri 11am–5pm, Sat 11am–3pm.",
      descZh: "Lett Thomas 当前展。开放时间周三至五 11am–5pm，周六 11am–3pm。",
      url: "https://lett-thomas.com/exhibition/peter-stichbury-4/" },
    { venue: "michaellett", title: "Imogen Taylor — opens 22 Jul", zh: "Imogen Taylor 个展", kind: "opening", date: "2026-07-22", price: "free",
      desc: "New exhibition by Imogen Taylor, 22 July – 22 August, at Lett Thomas.",
      descZh: "Imogen Taylor 新展开幕，展期 7月22日–8月22日。",
      url: "https://lett-thomas.com/exhibition/imogen-taylor-7/" },
    { venue: "starkwhite", title: "Martin Basher: Vermillion Sands", zh: "Martin Basher《Vermillion Sands》", kind: "exhibition", date: "2026-06-20", end: "2026-07-25", price: "free",
      desc: "Current show at Starkwhite Auckland, 510 Karangahape Rd.",
      descZh: "Starkwhite 奥克兰空间当前展。",
      url: "https://starkwhite.co.nz/exhibition/martin-basher-vermillion-sands/" },
    { venue: "teuru", title: "COSMOLOGIES — Nikau Hindin & Naminapu Maymuru-White", zh: "COSMOLOGIES：Nikau Hindin 与 Naminapu Maymuru-White", kind: "exhibition", date: "2026-05-31", end: "2026-08-09", price: "free",
      desc: "Aute (barkcloth) star maps meet Yolŋu river-of-stars paintings — a trans-Pacific cosmology dialogue.",
      descZh: "树皮布星图与 Yolŋu 星河绘画的跨太平洋宇宙观对话。",
      url: "https://teuru.org.nz/products/nikau-hindin-and-naminapu-maymuru-white-cosmologies" },
    { venue: "teuru", title: "all the forest stands with you", zh: "all the forest stands with you 群展", kind: "exhibition", date: "2026-05-31", end: "2026-08-09", price: "free",
      desc: "Group show tracing entanglements between the human and more-than-human (Emily Karaka, Zheng Bo & more).",
      descZh: "探讨人类与非人类世界纠缠关系的群展（Emily Karaka、郑波等）。",
      url: "https://teuru.org.nz/products/all-the-forest-stands-with-you" },
    { venue: "teuru", title: "Herehere — Faletau / Hawkins / Sagapolutele", zh: "Herehere 三人展", kind: "exhibition", date: "2026-05-16", end: "2026-07-26", price: "free",
      desc: "Tāmaki Makaurau as a meeting place — Tāmaki of a hundred lovers.",
      descZh: "以“百人之恋的塔玛基”为题，探讨奥克兰作为相遇之地。",
      url: "https://teuru.org.nz/products/herehere-kauri-hawkins-sione-faletau-raymond-sagapolutele" },
    { venue: "teuru", title: "Te Uru x Whitecliffe: Mahitahi", zh: "Mahitahi：Whitecliffe 研究生展", kind: "exhibition", date: "2026-06-20", end: "2026-08-23", price: "free",
      desc: "Postgraduate students of Whitecliffe in a dynamic series.",
      descZh: "Whitecliffe 艺术学院研究生系列展。",
      url: "https://teuru.org.nz/products/te-uru-x-whitecliffe-mahitahi" },
    { venue: "gowlangsford", title: "Claudia Kogachi: Another Day (Onehunga)", zh: "Claudia Kogachi《Another Day》（Onehunga）", kind: "exhibition", date: "2026-06-27", end: "2026-07-25", price: "free",
      desc: "Kogachi's inaugural Gow Langsford show — experience and fantasy collide in personal and cultural iconography.",
      descZh: "Kogachi 在 Gow Langsford 的首展：个人与文化图像中经验与幻想的碰撞。",
      url: "https://gowlangsfordgallery.co.nz/exhibitions/525-another-day-claudia-kogachi/" },
    { venue: "gowlangsford", title: "Michael Hight: The Seasons (City)", zh: "Michael Hight《The Seasons》（City 空间）", kind: "exhibition", date: "2026-07-08", end: "2026-08-08", price: "free",
      desc: "Landscapes across Aotearoa's seasons — Maniototo summer to Waitaki spring.",
      descZh: "横跨新西兰四季的风景：从 Maniototo 的夏到 Waitaki 的春。",
      url: "https://gowlangsfordgallery.co.nz/exhibitions/529-the-seasons-michael-hight/" },
    { venue: "northart", title: "Arrested Practice", zh: "Arrested Practice 群展", kind: "exhibition", date: "2026-07-18", end: "2026-08-03", price: "free",
      desc: "Ten artists revisit works once thought unfinished. Daily 10am–4pm, free.",
      descZh: "十位艺术家重访“未完成”之作。每日 10am–4pm，免费。",
      url: "https://www.northart.co.nz/" },
    { venue: "northart", title: "The Windows — drawing show selections", zh: "The Windows 橱窗绘画展", kind: "exhibition", date: "2026-07-17", end: "2026-08-26", price: "free",
      desc: "Selected drawings in Northart's full-scape windows — visible day and night.",
      descZh: "入选素描作品在整面橱窗展出，白天黑夜都能看。",
      url: "https://www.northart.co.nz/" },
    /* ---- 历史记录（真实，来源：artsdiary.co.nz 2025-12-12 快照）----
       无新排期的场馆卡片显示为"上次活动"；日期为撤展日，开展日为估算。 */
    { venue: "gusfisher",   title: "Eva During: Under the Bridge", zh: "Eva During《Under the Bridge》", kind: "exhibition", date: "2025-11-15", end: "2026-01-18", url: "https://gusfishergallery.auckland.ac.nz/" },
    { venue: "artspace",    title: "Echo — Erica Holm, Ngaroma Riley, Tarika Sabherwal", zh: "《Echo》三人展", kind: "exhibition", date: "2025-11-08", end: "2025-12-20", url: "https://artspace-aotearoa.nz/" },
    { venue: "objectspace", title: "Warwick Freeman: Hook Hand Heart Star", zh: "Warwick Freeman 首饰回顾展", kind: "exhibition", date: "2025-11-01", end: "2026-03-08", url: "https://objectspace.org.nz/" },
    { venue: "freshgallery", title: "Jim To'o Filiva'a Stretton: Echoes of the Pacific", zh: "《太平洋回声》", kind: "exhibition", date: "2025-11-22", end: "2026-01-10", url: "https://www.aucklandcouncil.govt.nz/" },
    { venue: "uxbridge",    title: "Pat Basse: Visual Diary of An Astral Traveller", zh: "Pat Basse 星旅视觉日记", kind: "exhibition", date: "2025-11-22", end: "2026-01-17", url: "https://uxbridge.org.nz/" },
    { venue: "papakura",    title: "ALESANA — Lealofitaute Vaai & Selu-Kian Lealiifano-Faletoese", zh: "《ALESANA》双人展", kind: "exhibition", date: "2025-11-15", end: "2026-01-31", url: "https://www.aucklandcouncil.govt.nz/" },
    { venue: "sanderson",   title: "Summer Exhibition 25-26 — gallery artists", zh: "画廊艺术家夏季群展", kind: "exhibition", date: "2025-12-01", end: "2026-02-01", url: "https://www.sanderson.co.nz/" },
    { venue: "corban",      title: "Molly Timmins: Nurturing Soil / Sur-Collective: Apapacho", zh: "双展：滋养土壤 / Apapacho", kind: "exhibition", date: "2025-12-06", end: "2026-02-07", url: "https://cebarts.org.nz/" },
    { venue: "franklin",    title: "Mike Tupaea: Te Oho The Awakening", zh: "Mike Tupaea《觉醒》", kind: "exhibition", date: "2025-12-06", end: "2026-02-07", url: "https://www.aucklandcouncil.govt.nz/" },
    { venue: "upstairs",    title: "Members Summer Show", zh: "会员夏季展", kind: "exhibition", date: "2025-12-01", end: "2026-01-18", url: "https://www.lopdell.org.nz/" },
    { venue: "studioone",   title: "Group show — Norman, Keen, Cowie, Nagels, Tubb, Nicholls", zh: "六人群展", kind: "exhibition", date: "2025-12-06", end: "2026-01-22", url: "https://studioone.org.nz/" },
    { venue: "mangere",     title: "8 Contemporary Cook Islands Artists", zh: "八位库克群岛当代艺术家", kind: "exhibition", date: "2025-12-13", end: "2026-02-14", url: "https://www.aucklandcouncil.govt.nz/" },
    { venue: "ivananthony", title: "Brendon Wilkinson: east, west, east direction is the yellow sky", zh: "Brendon Wilkinson 个展", kind: "exhibition", date: "2025-11-15", end: "2025-12-20", url: "#" },
    { venue: "melanieroger", title: "Peter Robinson", zh: "Peter Robinson 个展", kind: "exhibition", date: "2025-11-15", end: "2025-12-20", url: "#" },
    { venue: "bergman",     title: "New Collectors — Leleisi'uao, Fong, Good, McMillan & more", zh: "《新藏家》群展", kind: "exhibition", date: "2025-11-15", end: "2025-12-20", url: "#" },
    { venue: "coastalsigns", title: "Body Language — John Miller, Di Ffrench, Raukura Turei", zh: "《身体语言》三人展", kind: "exhibition", date: "2025-11-22", end: "2026-01-31", url: "#" },
    { venue: "tworooms",    title: "Robin White: Finding my way in Aomori", zh: "Robin White《青森寻路》", kind: "exhibition", date: "2025-11-08", end: "2025-12-20", url: "https://tworooms.co.nz/" },
    { venue: "artis",       title: "J. S. Parker: Plain Song — Station of the Soul", zh: "J. S. Parker《素歌》", kind: "exhibition", date: "2025-11-08", end: "2025-12-15", url: "#" },
    { venue: "jonathangrant", title: "Zarahn Tūwharetoa Southon: HĪTORI", zh: "Zarahn Tūwharetoa Southon《HĪTORI》", kind: "exhibition", date: "2025-11-15", end: "2025-12-15", url: "#" },
    { venue: "foenander",   title: "Haka — Bailey, Birch, Forde, Jahnke, Reihana, Waetford", zh: "《Haka》群展", kind: "exhibition", date: "2025-11-22", end: "2025-12-24", url: "#" },
    { venue: "pah",         title: "Yvonne Todd: Diary of a Carrot", zh: "Yvonne Todd《胡萝卜日记》", kind: "exhibition", date: "2025-12-13", end: "2026-03-22", url: "#" },

    /* 上线前清理（2026-07-07）：所有 Sample 假活动已删除——未校准的场馆如实显示灰色或"上次活动"。
       当前真实数据覆盖：AAG、Gow Langsford、Lett Thomas、Starkwhite、Te Uru、Northart、
       Poetry Live、五个每周集市，以及 21 条历史记录。其余待每周体检任务逐步补齐。 */
    // 2026-07-07 体检后仍无活动：unity / timeout / library / townhall / powerstation / freshgallery / nathan / pah / uxbridge 及多数 dealer 画廊 → 灰色贴纸
  ]
};
